// <auto-generated />
namespace agenda_angularjs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Setupinicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Setupinicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201810251725243_Setup-inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
